name: CI
on:
  push:
    paths-ignore:
      - 'demo/**'
      - 'docs/**'
      - '**.md'

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/bundler-audit@v1
      with:
        args: '--ignore CVE-2020-8161'
    - uses: workarea-commerce/ci/rubocop@v1
    - uses: workarea-commerce/ci/eslint@v1
      with:
        args: '{admin,core,storefront}/{app,test}/**/*.js'
    - uses: workarea-commerce/ci/stylelint@v1
      with:
        args: '{admin,core,storefront}/{app,test}/**/*.scss'

  admin_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd admin && bin/rails test -b

  admin_teaspoon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd admin && bin/rails teaspoon

  admin_system_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd admin && bin/rails test test/system/**/*_test.rb -b
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Admin Screenshots
        path: admin/test/dummy/tmp/screenshots

  core_teaspoon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd core && bin/rails teaspoon

  core_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd core && bin/rails test test/**/*_test.rb -b

  storefront_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd storefront && bin/rails test -b

  storefront_teaspoon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd storefront && bin/rails teaspoon

  storefront_system_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: cd storefront && bin/rails test test/system/**/*_test.rb -b
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Storefront Screenshots
        path: storefront/test/dummy/tmp/screenshots

  new_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        path: workarea
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Generate Application
      run: |
        cd ..
        mkdir my-store && cd my-store
        echo "source 'https://rubygems.org'" > Gemfile
        echo "gem 'rails'" >> Gemfile
        bundle install
        bundle exec rails new ./ --force \
        --skip-spring \
        --skip-active-record \
        --skip-action-cable \
        --skip-puma \
        --skip-coffee \
        --skip-turbolinks \
        --skip-bootsnap \
        --skip-yarn \
        --skip-bundle \
        --skip-webpack-install
        echo "gem 'workarea', path: '../workarea'" >> Gemfile
        bundle update
        bin/rails workarea:services:up
        bin/rails generate workarea:install
        bin/rails db:seed

  new_plugin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        path: workarea
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - run: gem install rails
    - name: Generate Plugin
      run: |
        cd ..
        rails plugin new my_plugin \
        --template=workarea/plugin_template.rb \
        --full \
        --skip-spring \
        --skip-active-record \
        --skip-action-cable \
        --skip-puma \
        --skip-coffee \
        --skip-turbolinks \
        --skip-bootsnap \
        --skip-yarn \
        --skip-webpack-install
